@startuml MathUtils
struct MathUtils {
    {static} + template <bool clear> DotProd(const Tensor<float>& a, const Tensor<float>& b, Tensor<float>& c) : void
    {static} + template <bool clear> DotProdTA(const Tensor<float>& a, const Tensor<float>& b, Tensor<float>& c) : void
    {static} + template <bool clear> DotProdTB(const Tensor<float>& a, const Tensor<float>& b, Tensor<float>& c) : void

    {static} + XorShift32(uint32_t state) : uint32_t
    {static} + FastRandFloat(uint32_t state) : float

    {static} + RoundTo(size_t alignment, size_t n) : size_t
}
@enduml
