@startuml NeuralNetwork
struct NeuralNetwork {
    - dataset : Dataset*
    - layers : vector<Layer>

    - YAML::Node* config

    + Define(YAML::Node& config, Dataset& dataset) : void

    + Load(std::ifstream& file) : void
    + Save(std::ofstream& file) const : void
    + LoadOptimizers(std::ifstream& file) : void
    + SaveOptimizers(std::ofstream& file) const : void

    + Forward() : void
    + Backward() : void
    + Score() : float
}
@enduml
