@startuml PackageLayout

actor User
participant Controller
participant LoadBalancer1
participant LoadBalancer2
participant Torpedo


== Connect & Capability Exchange ==
User -> Controller : Search()
Controller -> Torpedo : Broadcast(question)
Torpedo --> Controller : Answer(id, answer, key)
Controller -> Torpedo : Syn(id, uof)
Torpedo --> Controller : Ack(id, uof)


== Control -> Torpedo message formats ==
User -> Controller : UpdateTarget
Controller -> Torpedo : UpdateTarget(type=1, x=n, y=n, z=n)

User -> Controller : ChangeProx
Controller -> Torpedo : ChangeProx(type=2, prox=n)

User -> Controller : Detonate
Controller -> Torpedo : Detonate(type=3)

User -> Controller : ChangeFrq
Controller -> Torpedo : ChangeFrq(type=4, frq=n)


== Torpedo -> Control message formats ==
Torpedo --> Controller : CurrentPos(type=1, x=n, y=n, z=n, hdg=n)


== Controller -> LoadBalancer message formats ==
Controller -> LoadBalancer1 : AssignTorpedo(type=1, id=n, key=n, uof=n)


== General Flow ==
User -> Controller : Search
Controller -> Torpedo : Connect & Capability Exchange

Controller -> LoadBalancer1 : AssignTorpedo
Controller -> LoadBalancer2 : AssignTorpedo

alt EveryNTicks
    LoadBalancer1 -> Torpedo : UpdateTarget
    Torpedo --> LoadBalancer1 : CurrentPos

    LoadBalancer2 -> Torpedo : UpdateTarget
    Torpedo --> LoadBalancer2 : CurrentPos
end

alt WithinProx
        Torpedo -> : Detonate
end

Controller -> Torpedo : UserCommands
Torpedo --> Controller : CurrentPos

@enduml
